apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  username: U0E= # Base64 encoded username (e.g., "my_user_name")
  password: QWRtaW5AaW5mb2FuZTEyMw== # Base64 encoded password (e.g., "StrongPassword123")
