apiVersion: v1
kind: Service
metadata:
  name: coldfusion
spec:
  type: NodePort
  selector:
    app: coldfusion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30007
