name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: checkout-code
         uses: actions/checkout@v3
  
      -  name: create build directory
         run: |
              pwd
              ls -la
              mkdir build
              rsync -av ./ ./build --exclude build
              pwd
              zip -r ${{ github.workspace }}/build.zip build
              # mv build.zip ${{ github.workspace }}
              ls -l ${{ github.workspace }}

      -  name: Verify build.zip
         run: |
          pwd
          ls -l /home/runner/work/Cold_Fusion_Project/Cold_Fusion_Project
         
      -  name: build docker image
         run:  |
            ls -l
            docker build -t cold_fusion_6 /home/runner/work/Cold_Fusion_Project/Cold_Fusion_Project

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag cold_fusion_6 ${{ secrets.DOCKER_USERNAME }}/cold_fusion_7
          docker push ${{ secrets.DOCKER_USERNAME }}/cold_fusion_7


     
